theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
C-g = ":echo %sh{~/.config/helix/scripts/git-copy-permalink.sh %{buffer_name} %{selection_line_start} %{selection_line_end}}"
